# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    sudo adduser --home /srv/myservice --system --disabled-password --group myservice
    sudo cp /vagrant/upstart/myservice.conf /etc/init/myservice.conf
    sudo mkdir /srv/myservice/releases
    sudo mkdir /srv/myservice/releases/init
    sudo ln -sfT /srv/myservice/releases/init /srv/myservice/current
    sudo chown -R myservice:myservice /srv/myservice
    # install python?
  SHELL
end
